# Generated by Django 6.0 on 2025-12-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingAndReviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
    ]
