# Generated by Django 6.0 on 2025-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='android_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='desktop_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='ios_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
