# Generated by Django 6.0 on 2025-12-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0002_companydetails_android_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
