# Generated by Django 6.0 on 2025-12-15 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0004_companypaymentdetails_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='esewa_link',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='khalti_link',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='companypaymentdetails',
            name='upi_id',
        ),
        migrations.AddField(
            model_name='companypaymentdetails',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authentications.companydetails'),
        ),
        migrations.AddField(
            model_name='companypaymentdetails',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companypaymentdetails',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
