# Generated by Django 6.0 on 2025-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0006_serviceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
