# Generated by Django 6.0 on 2025-12-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0007_alter_serviceprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=10),
        ),
    ]
