# Generated by Django 5.0 on 2025-12-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentications', '0009_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
