# Generated by Django 6.0 on 2025-12-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='parent_phone',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='student_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
