# Generated by Django 6.0 on 2025-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0002_rename_phone_student_parent_phone_student_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('NURSERY', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', 'Grade I'), ('2', 'Grade II'), ('3', 'Grade III'), ('4', 'Grade IV'), ('5', 'Grade V'), ('6', 'Grade VI'), ('7', 'Grade VII'), ('8', 'Grade VIII'), ('9', 'Grade IX'), ('10', 'Grade X'), ('11', 'Grade XI'), ('12', 'Grade XII'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
