# Generated by Django 6.0 on 2025-12-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0003_student_section_alter_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldetails',
            name='school_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_image/'),
        ),
    ]
