# Generated by Django 6.0 on 2025-12-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0005_alter_schooldetails_user_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
