# Generated by Django 6.0 on 2025-12-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0006_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
