# Generated by Django 6.0 on 2025-12-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0009_remove_student_is_active_student_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name, e.g., 'Standard', 'Premium'", max_length=100)),
                ('width', models.IntegerField(default=350, help_text='Card width in pixels')),
                ('height', models.IntegerField(default=200, help_text='Card height in pixels')),
                ('background_color', models.CharField(default='#ffffff', help_text='Card background color (hex)', max_length=7)),
                ('photo_x', models.IntegerField(default=0, help_text='Photo X-coordinate')),
                ('photo_y', models.IntegerField(default=0, help_text='Photo Y-coordinate')),
                ('photo_width', models.IntegerField(default=80, help_text='Photo width in px')),
                ('photo_height', models.IntegerField(default=100, help_text='Photo height in px')),
                ('photo_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', help_text='Photo alignment', max_length=10)),
                ('logo_x', models.IntegerField(default=0, help_text='Logo X-coordinate')),
                ('logo_y', models.IntegerField(default=0, help_text='Logo Y-coordinate')),
                ('logo_width', models.IntegerField(default=60, help_text='Logo width in px')),
                ('logo_height', models.IntegerField(default=60, help_text='Logo height in px')),
                ('logo_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Logo alignment', max_length=10)),
                ('name_x', models.IntegerField(default=20)),
                ('name_y', models.IntegerField(default=30)),
                ('name_font_size', models.IntegerField(default=16)),
                ('name_font_color', models.CharField(default='#000000', max_length=7)),
                ('name_font_family', models.CharField(default='Arial', max_length=50)),
                ('name_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('roll_no_x', models.IntegerField(default=20)),
                ('roll_no_y', models.IntegerField(default=60)),
                ('roll_no_font_size', models.IntegerField(default=14)),
                ('roll_no_font_color', models.CharField(default='#333333', max_length=7)),
                ('roll_no_font_family', models.CharField(default='Verdana', max_length=50)),
                ('roll_no_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('class_x', models.IntegerField(default=20)),
                ('class_y', models.IntegerField(default=80)),
                ('class_font_size', models.IntegerField(default=14)),
                ('class_font_color', models.CharField(default='#333333', max_length=7)),
                ('class_font_family', models.CharField(default='Verdana', max_length=50)),
                ('class_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('section_x', models.IntegerField(default=20)),
                ('section_y', models.IntegerField(default=100)),
                ('section_font_size', models.IntegerField(default=14)),
                ('section_font_color', models.CharField(default='#333333', max_length=7)),
                ('section_font_family', models.CharField(default='Verdana', max_length=50)),
                ('section_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('barcode_x', models.IntegerField(default=10)),
                ('barcode_y', models.IntegerField(default=150)),
                ('barcode_width', models.IntegerField(default=120)),
                ('barcode_height', models.IntegerField(default=40)),
                ('barcode_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
