# Generated by Django 6.0 on 2025-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0010_idcardtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='barcode_alignment',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='barcode_height',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='barcode_width',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='barcode_x',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='barcode_y',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='class_alignment',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='class_font_color',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='class_font_family',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='class_font_size',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='class_x',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='class_y',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='height',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='logo_alignment',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='logo_height',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='logo_width',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='logo_x',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='logo_y',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='section_alignment',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='section_font_color',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='section_font_family',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='section_font_size',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='section_x',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='section_y',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='width',
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='template_image',
            field=models.ImageField(blank=True, help_text='Background image of the ID card template', null=True, upload_to='id_card_templates/'),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='photo_width',
            field=models.IntegerField(default=80),
        ),
    ]
