# Generated by Django 6.0 on 2025-12-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0011_remove_idcardtemplate_background_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='name_alignment',
            new_name='address_alignment',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='roll_no_font_color',
            new_name='address_font_color',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='roll_no_font_family',
            new_name='address_font_family',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='name_x',
            new_name='address_x',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='roll_no_alignment',
            new_name='dob_alignment',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='roll_no_font_size',
            new_name='dob_font_size',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='roll_no_x',
            new_name='dob_x',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='name_font_color',
            new_name='full_name_font_color',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='name_font_family',
            new_name='full_name_font_family',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='name_font_size',
            new_name='full_name_font_size',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='name_y',
            new_name='full_name_y',
        ),
        migrations.RenameField(
            model_name='idcardtemplate',
            old_name='roll_no_y',
            new_name='roll_y',
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='address_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='address_y',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='dob_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='dob_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='dob_y',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='email_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='email_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='email_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='email_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='email_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='email_y',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='full_name_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='full_name_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='gender_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='gender_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='gender_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='gender_font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='gender_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='gender_y',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='grade_y',
            field=models.IntegerField(default=240),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_name_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_name_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_name_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_name_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_name_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_name_y',
            field=models.IntegerField(default=160),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_phone_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_phone_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_phone_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_phone_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_phone_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='parent_phone_y',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='roll_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='roll_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='roll_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='roll_font_size',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='roll_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='school_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='school_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='school_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='school_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='school_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='school_y',
            field=models.IntegerField(default=220),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='section_y',
            field=models.IntegerField(default=260),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='student_phone_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='student_phone_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='student_phone_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='student_phone_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='student_phone_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='student_phone_y',
            field=models.IntegerField(default=140),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='valid_until_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='valid_until_font_color',
            field=models.CharField(default='#333333', max_length=7),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='valid_until_font_family',
            field=models.CharField(default='Verdana', max_length=50),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='valid_until_font_size',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='valid_until_x',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='valid_until_y',
            field=models.IntegerField(default=280),
        ),
    ]
