# Generated by Django 6.0 on 2025-12-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0012_rename_name_alignment_idcardtemplate_address_alignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='school',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_card_templates', to='MainApps.schooldetails'),
            preserve_default=False,
        ),
    ]
