# Generated by Django 6.0 on 2025-12-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0013_idcardtemplate_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='user',
        ),
    ]
