# Generated by Django 6.0 on 2025-12-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0014_remove_idcardtemplate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetails',
            name='school_student_id_card_template',
        ),
    ]
