# Generated by Django 6.0 on 2025-12-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0015_remove_schooldetails_school_student_id_card_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='card_status',
            field=models.CharField(choices=[('LOST', 'Lost'), ('RENEW', 'Renew'), ('New', 'New')], default='NEW', max_length=10),
        ),
    ]
