# Generated by Django 6.0 on 2025-12-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0016_student_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='card_status',
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('LOST', 'Lost'), ('REISSUED', 'Reissued'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20),
        ),
    ]
