# Generated by Django 6.0 on 2025-12-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0019_rename_address_active_idcardtemplate_address_tag_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='name',
        ),
    ]
