# Generated by Django 6.0 on 2025-12-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0020_remove_idcardtemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='photo_border_radius',
            field=models.IntegerField(default=0, help_text='Border radius in pixels (0 = square, 50 = circle)'),
        ),
    ]
