# Generated by Django 6.0 on 2025-12-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0021_idcardtemplate_photo_border_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='photo_border_radius',
        ),
    ]
