# Generated by Django 5.0 on 2025-12-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApps', '0024_alter_student_options_alter_student_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('LOST', 'Lost'), ('REISSUED', 'Reissued')], default='ACTIVE', max_length=20),
        ),
    ]
